IFP128
FuelLabs/sway-libs pull request #105
Opened 2023-02-28 10:21 UTC by rostyslavtyshko

## Type of change

- Bug fix
- New feature
- Improvement (refactoring, restructuring repository, cleaning tech debt, ...)
- Documentation
- Other (describe below)

## Changes

The following changes have been made:

- Change 1
- Change 2

## Notes

- Note 1

## Related Issues

Closes #\<issue number\>

2023-03-20 17:50 UTC, nfurfaro submitted a review, later dismissed

2023-03-28 15:34 UTC, bitzoic requested changes
Minor comments but looks good!

2023-03-28 15:34 UTC, bitzoic commented on libs/fixed_point/README.md
> +The Fixed Point Number library provides a library to use fixed-point numbers in Sway. It has 3 distinct unsigned types: `UFP32`, `UFP64` and `UFP128` as well as 2 signed types - `IFP64` and `IFP128`.
```suggestion
The Fixed Point Number library provides a library to use fixed-point numbers in Sway. It has 3 distinct unsigned types: `UFP32`, `UFP64`, and `UFP128` as well as 2 signed types - `IFP64` and `IFP128`. These types are stack allocated.

```

2023-03-28 15:34 UTC, bitzoic commented on libs/fixed_point/src/ifp128.sw
> +// A wrapper library around the  type for mathematical functions operating with signed 128-bit fixed point numbers.
```suggestion
// A wrapper library around the type for mathematical functions operating with signed 128-bit fixed point numbers.
```

2023-03-29 11:53 UTC, rostyslavtyshko commented on libs/fixed_point/src/ifp128.sw
> +        72
64 bits for `UFP64` + 8 bits for `bool`

2023-03-29 11:59 UTC, rostyslavtyshko commented on libs/fixed_point/README.md
> +The Fixed Point Number library provides a library to use fixed-point numbers in Sway. It has 3 distinct unsigned types: `UFP32`, `UFP64` and `UFP128` as well as 2 signed types - `IFP64` and `IFP128`.
Fixed

2023-03-29 11:59 UTC, rostyslavtyshko commented on libs/fixed_point/src/ifp128.sw
> +    /// Returns the nearest integer to `self`. Round half-way cases away from
Fixed

2023-03-29 11:59 UTC, rostyslavtyshko commented on libs/fixed_point/src/ifp128.sw
> +    fn sign_reverse(self) -> Self {
Made public

2023-03-29 13:54 UTC, bitzoic approved these changes
:shipit:

2023-03-29 14:52 UTC, merged