chore: fix some comments
FuelLabs/sway-libs pull request #271
Opened 2024-07-28 17:01 UTC by withbest

## Type of change

- Documentation

## Changes

-  fix some comments

## Notes

- Note 1

## Related Issues

Closes #\<issue number\>

## Checklist

- [ ] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.
- [ ] I have updated the changelog to reflect the changes on this PR.

2024-07-28 17:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FuelLabs/sway-libs?pullRequest=271) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FuelLabs/sway-libs?pullRequest=271) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FuelLabs/sway-libs?pullRequest=271) it.</sub>

2024-07-30 08:25 UTC, bitzoic approved these changes
Thanks for your contribution!

2024-07-30 08:27 UTC, bitzoic requested changes

2024-07-30 08:27 UTC, bitzoic commented on docs/contributing-book/src/code_docs/naming-components.md
> -### Ambigious Abbreviations
This was correct

2024-07-30 08:41 UTC, SwayStar123 commented on docs/contributing-book/src/code_docs/naming-components.md
> -### Ambigious Abbreviations
No, it should be Ambiguous

2024-08-15 20:07 UTC, K1-R1 approved these changes
Thanks!

2024-08-15 20:07 UTC, merged