UFP32
FuelLabs/sway-libs pull request #84
Opened 2023-01-24 12:58 UTC by rostyslavtyshko

## Type of change

- Bug fix
- New feature
- Improvement (refactoring, restructuring repository, cleaning tech debt, ...)
- Documentation
- Other (describe below)

## Changes

The following changes have been made:

- Change 1
- Change 2

## Notes

- Note 1

## Related Issues

Closes #\<issue number\>

2023-01-31 16:37 UTC, bitzoic requested changes
Could you update the README to state it now has 3 types [here](https://github.com/FuelLabs/sway-libs/blob/f33fc23bdfd4b57e6be31c43de7181899bf0d28c/libs/fixed_point/README.md?plain=1#L3)? 

There are also 15 build warnings, are they something that you are able to address?

Besides that LGTM 💪

2023-01-31 16:37 UTC, bitzoic commented on libs/fixed_point/src/ufp32.sw
> +        // Conversion to U128 done to ensure no overflow happen
```suggestion
        // Conversion to U64 done to ensure no overflow happen
```

2023-01-31 16:37 UTC, bitzoic commented on libs/fixed_point/src/ufp32.sw
> +// A wrapper library around the u32 type for mathematical functions operating with signed 64-bit fixed point numbers.
```suggestion
// A wrapper library around the u32 type for mathematical functions operating with unsigned 32-bit fixed point numbers.
```

2023-01-31 16:37 UTC, bitzoic commented on libs/fixed_point/src/ufp32.sw
> +use std::{math::*, u128::U128};
```suggestion
use std::math::*;
```
Unused import

2023-02-01 10:57 UTC, rostyslavtyshko commented on libs/fixed_point/src/ufp32.sw
> +// A wrapper library around the u32 type for mathematical functions operating with signed 64-bit fixed point numbers.
Fixed

2023-02-01 10:57 UTC, rostyslavtyshko commented on libs/fixed_point/src/ufp32.sw
> +use std::{math::*, u128::U128};
Fixed

2023-02-01 10:57 UTC, rostyslavtyshko commented on libs/fixed_point/src/ufp32.sw
> +        // Conversion to U128 done to ensure no overflow happen
Fixed

2023-02-01 14:36 UTC, bitzoic approved these changes
:shipit:

2023-02-02 14:45 UTC, merged